### ISSUE TITLE
protobuf 3.4.1-TypeError: Descriptors should not be created directly, but only retrieved from their parent-it's back

### ISSUE THREAD

**Issue by yuyuyak** [tgalal/python-axolotl#21]
Hi.  I'm aware this issue came about with protobuf 3.0+, and adding _pb2 to filenames solved it a while back.  I used it successfully with protobuf-3.2.1.  However in Gentoo we upgraded to protobuf-3.4.1 a couple of months ago and here it is again.  Unfortunately downgrading protobuf causes other issues here, so I finally had to give in and disable omemo in gajim (my use case for python-axolotl).  I confess I really don't know where to point my finger, but hoping someone here has an answer.  I've spent much time scouring the web on the issue, but can only find reference to the _pb2 issue.  Gentoo info is non-existent because python-axolotl is not officially available in the source tree, so I use the 0.1.39 ebuild here: https://gpo.zugaina.org/AJAX/Ebuild/27861724/View.
Here is the actual error as reported by gajim:
`Traceback (most recent call last):
  File "/home/myuser/.local/share/gajim/plugins/plugin_installer/plugin_installer.py", line 438, in on_plugin_downloaded
    plugins = self.scan_dir_for_plugin(plugin_dir)
  File "/home/myuser/.local/share/gajim/plugins/plugin_installer/plugin_installer.py", line 534, in scan_dir_for_plugin
    module = __import__(full_module_name)
  File "/home/myuser/.local/share/gajim/plugins/omemo/ui.py", line 33, in <module>
    from axolotl.state.sessionrecord import SessionRecord
  File "/home/myuser/.local/lib/python2.7/site-packages/axolotl/state/sessionrecord.py", line 3, in <module>
    from . import storageprotos
  File "/home/myuser/.local/lib/python2.7/site-packages/axolotl/state/storageprotos.py", line 41, in <module>
    options=None),
  File "/usr/lib/python2.7/site-packages/google/protobuf/descriptor.py", line 497, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors should not be created directly, but only retrieved from their parent.`
Thanks, and for the hard work on the port too.  Apologies in advance if I'm barking up the wrong tree.

**Comment by yuyuyak** [comment]
Wow, I should have looked closer before posting.  Gajim was using an old version of python-axolotl-0..35 I manually installed in my home dir, nuked that and all is fine now.  So sorry for the false alarm, have been tearing my hair out here.
Please close this issue.
