### ISSUE TITLE
Invalid padding bytes on decrypting with 0.2.2

### ISSUE THREAD

**Issue by lovetox** [tgalal/python-axolotl#32]
```
Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Gajim\Plugins\omemo\backend\state.py", line 137, in decrypt_message
    jid, omemo_message.sid, encrypted_key)
  File "C:\Users\User\AppData\Roaming\Gajim\Plugins\omemo\backend\state.py", line 274, in _process_message
    key = session_cipher.decryptMsg(message, textMsg=False)
  File "C:\msys64\mingw64\lib\python3.7\site-packages\axolotl\sessioncipher.py", line 74, in decryptMsg
    plaintext = self.decryptWithSessionRecord(sessionRecord, ciphertext)
  File "C:\msys64\mingw64\lib\python3.7\site-packages\axolotl\sessioncipher.py", line 106, in decryptWithSessionRecord
    plaintext = self.decryptWithSessionState(sessionState, cipherText)
  File "C:\msys64\mingw64\lib\python3.7\site-packages\axolotl\sessioncipher.py", line 144, in decryptWithSessionState
    plaintext = self.getPlaintext(messageVersion, messageKeys, ciphertextMessage.getBody())
  File "C:\msys64\mingw64\lib\python3.7\site-packages\axolotl\sessioncipher.py", line 198, in getPlaintext
    return cipher.decrypt(cipherText)
  File "C:\msys64\mingw64\lib\python3.7\site-packages\axolotl\sessioncipher.py", line 226, in decrypt
    return unpadder.update(decrypted) + unpadder.finalize()
  File "C:\msys64\mingw64\lib\python3.7\site-packages\cryptography\hazmat\primitives\padding.py", line 144, in finalize
    lib.Cryptography_check_pkcs7_padding)
  File "C:\msys64\mingw64\lib\python3.7\site-packages\cryptography\hazmat\primitives\padding.py", line 89, in _byte_unpadding_check
    raise ValueError("Invalid padding bytes.")
ValueError: Invalid padding bytes.

```

**Comment by lovetox** [comment]
@tgalal any idea? This is not a one time error, we are not able to decrypt messages anymore

**Comment by tgalal** [comment]
is there any way you could post steps I follow to reproduce the issue?

**Comment by lovetox** [comment]
```
    def encrypt(self, raw):
        if len(raw) % 16 != 0:
```
This evaluates for our code always to False, so padding is never applied on encryption

But it is forced on decryption and fails

**Comment by lovetox** [comment]
I will investigate now what we do differently, i have a hunch

**Comment by lovetox** [comment]
So what we do is we try to encrypt a key + auth tag which is 32 bytes long

32 % 16 = 0, means padding is never applied, but forced on decryption and fails because it finds None?

**Comment by tgalal** [comment]
Thanks, I'm now able to reproduce and working on a solution

**Comment by lovetox** [comment]
Btw you can close #31 its the same issue
